version: '3.9'
services:
  vault:
    image: vault:1.7.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: roottoken
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_SKIP_VERIFY: "true"
    cap_add:
      - IPC_LOCK
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exampledb
      POSTGRES_PASSWORD: exampledb
      POSTGRES_DB: exampledb

  app:
    build: ./
    container_name: vault_test_app
    ports:
      - "8000:8000"
    environment:
      APPROLE_ID: exampledb
      APPROLE_SECRET_ID: b5670ecc-1845-a9d7-5c42-df570d64a101
      VAULT_ADDR: vault:8200
